###
#username обновлять
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "Вася",
  "username": "Vasiliy87781",
  "password": "123123",
  "confirmPassword": "123123"
}

<> 2023-11-22T150424.200.json
<> 2023-11-22T145736.200.json
<> 2023-11-22T145332.200.json
<> 2023-11-22T145014.200.json

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "Vasiliy87781",
  "password": "123123"
}

<> 2023-11-22T151502.200.json
<> 2023-11-22T151242.200.json
<> 2023-11-22T151210.200.json
<> 2023-11-22T151208.200.json
<> 2023-11-22T151126.200.json
<> 2023-11-22T151035.200.json
<> 2023-11-22T150907.200.json
<> 2023-11-22T150427.200.json
<> 2023-11-22T150412.400.txt
<> 2023-11-22T150409.400.txt
<> 2023-11-22T150406.400.txt
<> 2023-11-22T150307.200.json
<> 2023-11-22T145801.200.json
<> 2023-11-22T145354.200.json

###
POST http://localhost:8080/api/signout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWYXNpbGl5ODc3ODEiLCJleHAiOjE3MDA2NTUzNjJ9.GmCNYWhjTuE-Eqzz647CsiO_IZy2yY_Sws4R4RbVQQg"
}

###
POST http://localhost:8080/api/v1/course
Content-Type: application/json

{}

###
POST http://localhost:8080/api/v1/course/full
Content-Type: application/json

{
  "id": "5fc2a1b62bb4473794ea7f4c",
  "creatorUserId": "4",
  "tittlePage": {
    "mrsuInfo": "МИНОБРНАУКИ РОСИИ\nФедеральное государственное бюджетное образовательное учреждение высшего образования\n\"Национальный исследовательский мордовский государственный университет им. Н.П. Огарева\"",
    "Fio": "Кузнецова Анна Владимировна",
    "tittle": "Продвинутый курс по литературе",
    "courseType": "Literature",
    "city": "Saransk"
  },
  "secondPage": {
    "udk": "82-3",
    "bbk": "888.4",
    "recenzents": [
      "Смирнов И.А., доктор филологических наук, профессор литературы",
      "Попова О.В., кандидат филологических наук, доцент культурологии"
    ],
    "extendedInfo": "Этот курс предоставляет глубокие знания по литературе и литературоведению.",
    "aboutAuthor": "Автор - Кузнецова А.В., исследователь в области литературы и культуры.",
    "issuesAreCovered": "Курс охватывает различные литературные направления, историю и современность литературы.",
    "thisCourseFor": "Предназначено для студентов и профессионалов, углубленно интересующихся литературой."
  },
  "learningResults": "По окончании курса студенты получат глубокие знания в области литературы и литературоведения.",
  "creator": {
    "id": "4",
    "FIO": "Кузнецова Анна Владимировна",
    "description": "Исследователь в области литературы и культуры, автор нескольких научных статей."
  },
  "recenzents": [
    "Смирнов И.А., доктор филологических наук, профессор литературы",
    "Попова О.В., кандидат филологических наук, доцент культурологии"
  ],
  "thisCourseFor": "Пособие предназначено для студентов и профессионалов, углубленно интересующихся литературой.",
  "usedSources": [
    {
      "authorName": "Кузнецова А.В.",
      "sourseType": "Научные статьи",
      "info": "История развития литературы"
    },
    {
      "authorName": "Смирнов И.А.",
      "sourseType": "Учебник",
      "info": "Современные течения в литературоведении"
    }
  ],
  "createdAt": "2023-11-27T09:00:00.000Z",
  "sections": [
    {
      "title": "Классическая литература",
      "description": "Введение в классическую литературу.",
      "subSections": [
        {
          "tittle": "Произведения",
          "content": [
            {
              "contentType": "LECTION",
              "body": "Этот урок предоставляет обзор классических произведений."
            },
            {
              "contentType": "TEST",
              "body": "Тестирование знаний по классической литературе."
            }
          ]
        },
        {
          "tittle": "Эпохи",
          "content": [
            {
              "contentType": "LECTION",
              "body": "Разбор литературных эпох и их особенностей."
            },
            {
              "contentType": "PICTURE",
              "body": "Графическое представление различных литературных эпох."
            }
          ]
        }
      ]
    },
    {
      "title": "Современная литература",
      "description": "Глубокое погружение в современные литературные течения.",
      "subSections": [
        {
          "tittle": "Современные авторы",
          "content": [
            {
              "contentType": "LECTION",
              "body": "Изучение современных авторов и их творчества."
            },
            {
              "contentType": "TABLE",
              "body": "Таблица сравнения различных современных литературных направлений."
            }
          ]
        },
        {
          "tittle": "Современные течения",
          "content": [
            {
              "contentType": "LECTION",
              "body": "Основы современных течений в литературе."
            },
            {
              "contentType": "TEST",
              "body": "Тест на знание современных литературных течений."
            }
          ]
        }
      ]
    }
  ],
  "tags": ["literature", "classics", "modern-literature"]
}

###
GET http://localhost:8080/api/v1/course

<> 2023-11-27T112712.503.json
<> 2023-11-27T112619.500.json
<> 2023-11-27T111600.500.json
<> 2023-11-27T111421.500.json
<> 2023-11-27T110819.503.json
<> 2023-11-27T110817.503.json
<> 2023-11-27T110815.503.json
<> 2023-11-27T110812.503.json
<> 2023-11-27T110809.503.json
<> 2023-11-27T110741.500.json
<> 2023-11-27T110529.404.json
<> 2023-11-27T110527.404.json
<> 2023-11-27T110523.404.json
<> 2023-11-27T110327.500.json
<> 2023-11-27T024939.200.json
<> 2023-11-27T024936.503.json
<> 2023-11-27T024913.503.json
<> 2023-11-27T024912.503.json
<> 2023-11-27T024307.200.json
<> 2023-11-27T024306.200.json
<> 2023-11-27T024301.200.json
<> 2023-11-27T024236.503.json
<> 2023-11-27T024229.503.json
<> 2023-11-27T024227.503.json
<> 2023-11-27T024225.503.json
<> 2023-11-27T024159.503.json
<> 2023-11-27T024157.503.json
<> 2023-11-27T024156.503.json
<> 2023-11-27T024154.503.json
<> 2023-11-27T024153.503.json
<> 2023-11-27T024151.503.json
<> 2023-11-27T024150.503.json
<> 2023-11-27T024132.503.json
<> 2023-11-27T024131.503.json
<> 2023-11-27T022637.200.json
<> 2023-11-27T020700.200.json
<> 2023-11-27T014032.200.json
<> 2023-11-27T013846.200.json
<> 2023-11-27T013843.503.json
<> 2023-11-27T013842.503.json
<> 2023-11-27T013838.503.json
<> 2023-11-27T013837.503.json
<> 2023-11-27T013755.200.json
<> 2023-11-27T013710.200.json
<> 2023-11-27T013620.200.json
<> 2023-11-27T013532.404.json
<> 2023-11-27T013527.404.json
<> 2023-11-27T013524.404.json
<> 2023-11-27T013334.503.json
<> 2023-11-27T013329.503.json
